baseURL = "https://ibraheem-portfolio.netlify.app/"
languageCode = "en-us"
title = "Muhammad Ibraheem"
theme = "alexa-portfolio"
googleAnalytics = "UA-167869327-1"
enableRobotsTXT = true


[params]
  # favicon = "./images/png.jpeg"
  home_title = "Hi, I am Ibraheem"
  home_subtitle = "Front-End Web Developer"
  linkedin = "https://www.linkedin.com/in/muhammad-ibraheem-512513292/"
  email = "muhammadibraheem.dev@gmail.com"
  phone = "+92-336-0505569"
  location = "Punjab, Pakistan"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[images]
  STATIC_URL = "static/images/garden-site-image.png"
